# Generated by Django 5.0.2 on 2024-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_templateformat"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="file_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
