# Generated by Django 5.0.2 on 2024-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_uploadedimage_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="remaining_products",
            field=models.IntegerField(default=0),
        ),
    ]
