# Generated by Django 5.0.3 on 2024-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_product_remaining_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRate",
            fields=[
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_unit",
                    models.CharField(
                        default="solana",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("target_currency", models.CharField(default="usd", max_length=10)),
            ],
        ),
    ]
